language: ruby

rvm:
  - 1.9.3

before_script:
  - "npm install -g grunt testacular@canary"
  - "grunt html2js"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "./script/ci_all"
