language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

services:
  - mongodb

before_script:
  - "npm install -g grunt-cli karma"
  - "npm install grunt"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "./script/ci_all"
