#!/bin/bash

# Start test backend instance
bundle exec thin start -R config.ru -e test -p 3001 -d

# Wait for thin
sleep 1

karma start spec/javascripts/config/karma-e2e.conf.js --single-run
RESULT=$?

# Kill test backend instance
kill `cat tmp/pids/thin.pid`
exit $RESULT
